{{- if and .Values.rbac.create .Values.rbac.clusterRole.enabled -}}
{{- include "base.validateRBAC" . -}}
{{- if eq (len .Values.rbac.clusterRole.rules) 0 }}
  {{- fail "rbac.clusterRole.rules cannot be empty when rbac.clusterRole.enabled is true" }}
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    {{- with .Values.rbac.clusterRole.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.rbac.clusterRole.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
