{{- if and .Values.rbac.create .Values.rbac.clusterRole.enabled .Values.rbac.clusterRoleBinding.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    {{- with .Values.rbac.clusterRoleBinding.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "base.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "base.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
