{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base.fullname" . }}
  {{- if .Values.configmap.name }}
  name: {{ .Values.configmap.name }}
  {{- end }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    {{- with .Values.configmap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configmap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if or .Values.configmap.data .Values.configmap.binaryData }}
data:
  {{- with .Values.configmap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- if .Values.configmap.binaryData }}
binaryData:
  {{- toYaml .Values.configmap.binaryData | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}