{{- if .Values.configmap.enabled -}}
{{- if not (or .Values.configmap.data .Values.configmap.binaryData) }}
  {{- fail "ConfigMap is enabled but neither data nor binaryData is set. Please configure at least one of these values." }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name | default (include "base.fullname" .) }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    {{- with .Values.configmap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configmap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.configmap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- if .Values.configmap.binaryData }}
binaryData:
  {{- toYaml .Values.configmap.binaryData | nindent 2 }}
{{- end }}
{{- end }}