{{- include "base.validatePersistentVolumes" . -}}
{{- range .Values.persistentVolumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "base.fullname" $ }}-{{ .name }}
  labels:
    {{- include "base.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  storageClassName: {{ .storageClassName }}
  resources:
    requests:
      storage: {{ .storage }}
---
{{- end }}