{{- if and .Values.rbac.create (not .Values.rbac.clusterRole.enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    {{- with .Values.rbac.role.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.rbac.role.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
